#!/bin/bash

# See Run345MHzA work in process to get to a perfect Run345MHz

~/Documents/DACSS/bin/Release/345MHz &


#rtl_sdr -f 345000000 -s 250000 -g49.6  /tmp/stream &  

read -p "Any key to exit"
# If I don't kill 345MHz it will write the log file and terminate anyway.
#pkill 345MHz
pkill rtl_sdr

#Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 
# 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 
# 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6 

#The RTL2832U can sample from two ranges ...
#225001 to 300000 and 900001 to 3200000.
#Pick any number that lies in either of those two ranges